### ISSUE TITLE
Please add researchers and faculty from WING NUS

### ISSUE THREAD

**Issue by knmnyn** [nus-deep-learning/about#1]
Hi all:

You can add the students and faculty from WING, thanks.  You should also approach Wang Wei's group for his input.

Animesh Prasad - http://wing.comp.nus.edu.sg/~animesh/
Muthu Chandrasekaran - http://wing.comp.nus.edu.sg/~cmkumar/ 
Wenqiang Lei - https://www.linkedin.com/in/wenqiang-lei-a94332a3/

Kan Min-Yen - http://www.comp.nus.edu.sg/~kanmy/

Add your own profs too!

**Comment by ritchieng** [comment]
Will do! Thanks for suggesting, I will add in by today.

**Comment by knmnyn** [comment]
Thanks!

**Comment by ritchieng** [comment]
Done, I added you officially to the group too, do accept the invitation :)
